### ISSUE TITLE
找不到元素

### ISSUE THREAD

**Issue by TianYou899** [Mr-Lizhibo/seckill_taobao#1]
我对比了一下路径完全一直，就是找不到元素，想问下大佬用的什么浏览器，我目前使用的chrome

**Comment by TianYou899** [comment]
^CTraceback (most recent call last):
  File "/Users/ty/Documents/MT/TB/taobao.py", line 31, in iselement
    browser.find_element_by_xpath(xpaths)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_xpath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ty/Documents/MT/TB/taobao.py", line 85, in <module>
    a.openChromeToTaobao()
  File "/Users/tianyou/Documents/MT/TB/taobao.py", line 54, in openChromeToTaobao
    isLogin = taobao.iselement(driver, '/html/body/div[2]/div/div/div[2]/div/div[1]/form/div[3]/input')
  File "/Users/tianyou/Documents/MT/TB/taobao.py", line 31, in iselement
    browser.find_element_by_xpath(xpaths)
KeyboardInterrupt

ty@tydeMacBook-Pro-2 TB %

**Comment by TianYou899** [comment]
已解决
